<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AV-L7300-1024" ignored="0" name="Default test" tests="7" failures="7" timestamp="29 Sep 2021 03:30:55 GMT" time="1231.44" errors="0">
  <testcase name="TestCase115_Shipto_Germany_Shipfrom_GreatBrighton" time="184.43" classname="TestCases.Regression.VAT">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	OpportuntiesPostGetTax Expected:TemporaryAnd Actual:Saved expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
OpportuntiesPostGetTax Expected:TemporaryAnd Actual:Saved expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at TestCases.Regression.VAT.calculateVATTax(VAT.java:158)
at TestCases.Regression.VAT.TestCase115_Shipto_Germany_Shipfrom_GreatBrighton(VAT.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestCase115_Shipto_Germany_Shipfrom_GreatBrighton -->
  <testcase name="TestCase116_Shipto_France_Shipfrom_GreatBrighton" time="175.162" classname="TestCases.Regression.VAT">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	OpportuntiesPostGetTax Expected:TemporaryAnd Actual:Saved expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
OpportuntiesPostGetTax Expected:TemporaryAnd Actual:Saved expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at TestCases.Regression.VAT.calculateVATTax(VAT.java:158)
at TestCases.Regression.VAT.TestCase116_Shipto_France_Shipfrom_GreatBrighton(VAT.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestCase116_Shipto_France_Shipfrom_GreatBrighton -->
  <testcase name="TestCase117_Shipto_US_Shipfrom_GreatBrighton" time="168.962" classname="TestCases.Regression.VAT">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Opportunities Total Tax Expected:77.50And Actual:72.50 expected [true] but found [false],
	OpportuntiesPostGetTax Expected:TemporaryAnd Actual:Saved expected [true] but found [false],
	Quotes Expected:155.00And Actual:145.00 expected [true] but found [false],
	Orders Total-Tax Expected:77.50And Actual:72.50 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Opportunities Total Tax Expected:77.50And Actual:72.50 expected [true] but found [false],
OpportuntiesPostGetTax Expected:TemporaryAnd Actual:Saved expected [true] but found [false],
Quotes Expected:155.00And Actual:145.00 expected [true] but found [false],
Orders Total-Tax Expected:77.50And Actual:72.50 expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at TestCases.Regression.VAT.calculateVATTax_BlankInvoiceMessaging(VAT.java:228)
at TestCases.Regression.VAT.TestCase117_Shipto_US_Shipfrom_GreatBrighton(VAT.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestCase117_Shipto_US_Shipfrom_GreatBrighton -->
  <testcase name="TestCase118_Shipto_GreatBrighton_Shipfrom_US" time="170.975" classname="TestCases.Regression.VAT">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	OpportuntiesPostGetTax Expected:TemporaryAnd Actual:Saved expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
OpportuntiesPostGetTax Expected:TemporaryAnd Actual:Saved expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at TestCases.Regression.VAT.calculateVATTax_BlankInvoiceMessaging(VAT.java:228)
at TestCases.Regression.VAT.TestCase118_Shipto_GreatBrighton_Shipfrom_US(VAT.java:74)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestCase118_Shipto_GreatBrighton_Shipfrom_US -->
  <testcase name="TestCase119_Shipto_US_Shipfrom_US" time="170.69" classname="TestCases.Regression.VAT">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Opportunities Total Tax Expected:77.50And Actual:72.50 expected [true] but found [false],
	OpportuntiesPostGetTax Expected:TemporaryAnd Actual:Saved expected [true] but found [false],
	Quotes Expected:155.00And Actual:145.00 expected [true] but found [false],
	Orders Total-Tax Expected:77.50And Actual:72.50 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Opportunities Total Tax Expected:77.50And Actual:72.50 expected [true] but found [false],
OpportuntiesPostGetTax Expected:TemporaryAnd Actual:Saved expected [true] but found [false],
Quotes Expected:155.00And Actual:145.00 expected [true] but found [false],
Orders Total-Tax Expected:77.50And Actual:72.50 expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at TestCases.Regression.VAT.calculateVATTax_BlankInvoiceMessaging(VAT.java:228)
at TestCases.Regression.VAT.TestCase119_Shipto_US_Shipfrom_US(VAT.java:79)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestCase119_Shipto_US_Shipfrom_US -->
  <testcase name="TestCase120_Shipto_AUS_Shipfrom_GreatBrighton" time="167.879" classname="TestCases.Regression.VAT">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	OpportuntiesPostGetTax Expected:TemporaryAnd Actual:Saved expected [true] but found [false],
	Opportunities Total Tax Expected:0.00And Actual:100.00 expected [true] but found [false],
	Quotes Expected:0.00And Actual:200.00 expected [true] but found [false],
	Orders Total-Tax Expected:0.00And Actual:100.00 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
OpportuntiesPostGetTax Expected:TemporaryAnd Actual:Saved expected [true] but found [false],
Opportunities Total Tax Expected:0.00And Actual:100.00 expected [true] but found [false],
Quotes Expected:0.00And Actual:200.00 expected [true] but found [false],
Orders Total-Tax Expected:0.00And Actual:100.00 expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at TestCases.Regression.VAT.calculateVATTax_AustraliaAddress(VAT.java:303)
at TestCases.Regression.VAT.TestCase120_Shipto_AUS_Shipfrom_GreatBrighton(VAT.java:84)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestCase120_Shipto_AUS_Shipfrom_GreatBrighton -->
  <testcase name="TestCase121_Shipto_GreatBrighton_Shipfrom_AUS" time="168.052" classname="TestCases.Regression.VAT">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	OpportuntiesPostGetTax Expected:TemporaryAnd Actual:Saved expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
OpportuntiesPostGetTax Expected:TemporaryAnd Actual:Saved expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at TestCases.Regression.VAT.calculateVATTax_AustraliaAddress(VAT.java:303)
at TestCases.Regression.VAT.TestCase121_Shipto_GreatBrighton_Shipfrom_AUS(VAT.java:89)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestCase121_Shipto_GreatBrighton_Shipfrom_AUS -->
</testsuite> <!-- Default test -->
